name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup .NET 2.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: Test Result
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: '*.trx'
        reporter: dotnet-trx 
    
  report:
    runs-on: windows-latest
    steps:
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Test Result
          path: '*.trx'
          reporter: dotnet-trx 
